---
name: build

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  core:
    strategy:
      matrix:
        go-version: [1.19.x, 1.20.x]
        platform: [ubuntu-latest]
    name: Build
    runs-on: ${{ matrix.platform }}
    env:
      GOBIN: /home/runner/.local/bin
    steps:
    - name: Install Go
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go-version }}
      id: go
    - name: Check out code into the Go module directory
      uses: actions/checkout@v3
    - name: Amend Environment Path
      run: |
        mkdir -p /home/runner/.local/bin
        echo "/home/runner/.local/bin" >> $GITHUB_PATH
    - name: Install prerequisites
      run: |
        sudo apt-get --assume-yes install make
        sudo apt-get --assume-yes install libnss3-tools
        sudo apt-get update
    - name: Install Go modules
      run: |
        make dep
        go mod tidy
        go mod verify
        go mod download
    - name: Build App
      run: |
        make